### ISSUE TITLE
24.7.0: setuptools is now a dependency

### ISSUE THREAD

**Issue by sigma67** [twisted/incremental#102]
setuptools now seems to be a default dependency of this package, where it wasn't with 22.10.0.

This is causing issues for us, as `incremental` is being pulled in through towncrier's default dependencies, so now `setuptools` is part of our dependency chain, where previously it wasn't.

**Comment by adiroiban** [comment]
Thanks for the report.

Not sure what we can do here for `incremental`.

This change was introduced 3 years ago in https://github.com/twisted/incremental/pull/59

--------

Note that the plan for `towncrier` is to remove the dependency on `incremental`

If you have time, you can help with the task on `tonwcrier` 

Cheers

**Comment by sigma67** [comment]
Ah thanks, that's good to know! Will do if I find time
