### ISSUE TITLE
Make it clear that 'use_incremental' is a custom setup extension

### ISSUE THREAD

**Issue by adiroiban** [twisted/incremental#3]
When used in external projects, at first I was confused about the `use_incremental` argument for setup as I thought it was a standard setuptools argument,

maybe it can be renamed x_use_incremental or some other name to suggest that if people want to know more about that argument they should search in hawkowl/incremental and not in setuptools

**Comment by twm** [comment]
I don't think that this is worth doing as the `use_foo` idiom is incompatible with `pyproject.toml`. I've had to introduce a different approach to address #90.
