### ISSUE TITLE
Auto generated file is not compatible with black

### ISSUE THREAD

**Issue by moshez** [twisted/incremental#55]
Is it possible to either make it compatible or have a `--black-compatible` explicit flag?

(I redacted the name of the internal project below, everything else is copy/paste.)

```
$ black src/
reformatted /Users/mzadka/src/<REDACTED>/src/<REDACTED>/_version.py
All done! ✨ 🍰 ✨
1 file reformatted, 12 files left unchanged.
$ git diff
diff --git a/src/<REDACTED>/_version.py b/src/<REDACTED>/_version.py
index a4efef1..1cc8fa1 100644
--- a/src/<REDACTED>/_version.py
+++ b/src/<REDACTED>/_version.py
@@ -7,5 +7,5 @@ Provides <REDACTED> version information.
 
 from incremental import Version
 
-__version__ = Version('<REDACTED>', 20, 7, 1)
+__version__ = Version("<REDACTED>", 20, 7, 1)
 __all__ = ["__version__"]
```

**Comment by adiroiban** [comment]
+1 for making it compatible by default without any flag.

**Comment by rodrigc** [comment]
Black was enabled by default for formatting the code in Twisted core: https://twistedmatrix.com/pipermail/twisted-python/2020-September/065220.html

So I think making incremental compatible with black (with no special flags) is a fine thing to do

**Comment by rodrigc** [comment]
@moshez can you try this branch: https://github.com/twisted/incremental/pull/60
