### ISSUE TITLE
Have PEP440 normalized release candidate

### ISSUE THREAD

**Issue by adiroiban** [twisted/incremental#81]
This change was introduced here https://github.com/twisted/incremental/pull/62/files#diff-37e20d1852a6db96a5d77c800f2007c0265b65a30a62649dbb7c0fd1228eef72R207

From PEP440 https://peps.python.org/pep-0440/#pre-release-separators

Pre-releases should allow a ., -, or _ separator between the release segment and the pre-release segment. The normal form for this is without a separator. This allows versions such as 1.1.a1 or 1.1-a1 which would be normalized to 1.1a1. It should also allow a separator to be used between the pre-release signifier and the numeral. This allows versions such as 1.0a.1 which would be normalized to 1.0a1.

--------

I am reporting this issue as in Towncrier there is a test that checks that towncrier version is the same as the importlib version ... but for a release candidate, the test fails.

----

I am not sure if this is a valid bug report, as in theory the current format is still valid PEP440, is just that it is not normalized.

**Comment by twm** [comment]
Agreed, it looks like the [current versioning spec](https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers) defines canonical without the dot/dash/underscore:

>     [N!]N(.N)*[{a|b|rc}N][.postN][.devN]

PEP 440 has been marked historical. We should change this behavior.

**Comment by twm** [comment]
#95 addresses this by removing the dot.
