### ISSUE TITLE
Dependency cycle with twisted

### ISSUE THREAD

**Issue by D3vil0p3r** [twisted/incremental#88]
Hello,
I was checking several repositories maintaining [python-incremental](https://archlinux.org/packages/extra/any/python-incremental/) and [python-twisted](https://archlinux.org/packages/extra/any/python-twisted/) where `incremental` depends on `twisted`, and `twisted` depends on `incremental`.

I checked  [setup.py](https://github.com/twisted/incremental/blob/trunk/setup.py) but I don't see any thing saying that `incremental` depends on `twisted`.

So, is `twisted` a mandatory dependency on `incremental`?

**Comment by D3vil0p3r** [comment]
@adiroiban

**Comment by adiroiban** [comment]
Hi

Can you give an example of such a repository ?

--------

The hard dependencies are here

https://github.com/twisted/incremental/blob/5752c86d01e3fb188b65ef3a1a31427717184f6d/setup.cfg#L23-L25

There is the optional `incremantal[scripts]` that depends on twisted

https://github.com/twisted/incremental/blob/5752c86d01e3fb188b65ef3a1a31427717184f6d/setup.cfg#L43-L46

**Comment by D3vil0p3r** [comment]
Thank you for the answer @adiroiban . Just click on the linked [python-incremental](https://archlinux.org/packages/extra/any/python-incremental/) and [python-twisted](https://archlinux.org/packages/extra/any/python-twisted/). They are from Arch Linux repository. Look the **Dependencies** sectiion.

**Comment by adiroiban** [comment]
Hi

The Arch packages are created by Arch developers and should be reported downstrem

We are only handling the pip packages.

Regards

**Comment by D3vil0p3r** [comment]
> Hi
> 
> The Arch packages are created by Arch developers and should be reported downstrem
> 
> We are only handling the pip packages.
> 
> Regards

Yes. In order to address this, my question is: is `twisted` a mandatory dependency on `incremental`? Or optional dependency? If no, I can report it to Arch Linux maintainers.

**Comment by adiroiban** [comment]
If you want to use incremental command line tools, `twisted` is mandatory.

If you only want to use the incremental API, it is not manadatory.

Hope it helps.

I am happy to review a PR that removes twisted/twisted as a dependency.
