### ISSUE TITLE
apidocs build is failing to publish

### ISSUE THREAD

**Issue by twm** [twisted/incremental#98]
The apidocs build is [failing to publish](https://github.com/twisted/incremental/actions/runs/10100878412/job/27933238014) to GitHub pages and has been for [at least 6 months](https://github.com/twisted/incremental/actions/runs/7729103510/job/21071501327).

**Comment by twm** [comment]
(The API hasn't changed so this is not urgent.)

**Comment by adiroiban** [comment]
The issue is due to GitHub Actions workflow permissions.

The token on has

```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
```

For the publish job we also need to add `content: write`
